
[INCLUDE]
INCLUDE = common/materials_track.ini, common/conditions.ini, common/grass_fx.ini

[ABOUT]
AUTHOR = Den_88

[LIGHTING]
SPECULAR_MULT=1
LIT_MULT=1 

[BOUNCED_LIGHT]
SUPPORTED = 1
SURFACE_MATERIALS = ?
OCCLUDING_MATERIALS = 
OBJECT_MATERIALS = ?

[WIND]
DYNAMIC_FLAGS = AUTO

[BASIC]
SUPPORTS_WIND = 1

[SOL2]
HORIZON_OFFSET = 0.0
DOME_SIZE = 14000
SUN_DAWN = 1
SUN_DUSK = 1
FOG_LEVEL = 0.90
FOG_BLEND = 1.15
FOG_DISTANCE = 0.9
SMOG_MORNING = 0.05
SMOG_NOON = 0.1
SMOG_EVENING = 0.15
EXPOSURE_FIX = 1.0

[PURE]
ACTIVE= 1
SUN_DAWN = 1
SUN_DUSK = 1
FOG_LEVEL = 0.05
FOG_BLEND = 1.15
FOG_DISTANCE = 0.9
SMOG_MORNING = 0.05
SMOG_NOON = 0.1
SMOG_EVENING = 0.15

[Material_Water]
Materials = water
Type = LAKE
UseNormalMapTwice=0
UseAlphaFromDiffuse=0

[SHADER_REPLACEMENT_...]
MESHES = material:water
DEPTH_MODE = NORMAL
IS_TRANSPARENT = 0

[SHADER_REPLACEMENT_...]
MATERIALS = box_windows,glass_t
IS_TRANSPARENT = 1
BLEND_MODE = ALPHA_BLEND
DOUBLE_FACE_SHADOW_BIASED=1
CULL_MODE = NONE
PROP_... = ksAlphaRef,0.5

[SHADER_REPLACEMENT_...]
MATERIALS=box_red,cl
DOUBLE_FACE_SHADOW_BIASED=1
CULL_MODE = NONE

[LOCAL_CUBEMAP_...]
MESHES = Decap.025_SUB2
POSITION = -58.56, 2.98, 108.67
OFFSET = 0, 0, 0   
EXCLUDE = 
CLIP_PLANE_NEAR = 2 
HIGH_RESOLUTION = 1 
LOW_RESOLUTION = 0 
IS_DYNAMIC = 1  
DYNAMIC_FAST = 0 
STATIC_FACES = TOP, LEFT, REAR, BOTTOM  
INCLUDE_SKY = 1  
INCLUDE_CARS = 0  
DYNAMIC_LIGHTING = 1   
DEBUG = 0  

[LOCAL_CUBEMAP_...]
MESHES = Decap.026_SUB1
POSITION = -0.327, 1.02, 4.73
OFFSET = 0, 0, 0   
EXCLUDE = 
CLIP_PLANE_NEAR = 2 
HIGH_RESOLUTION = 1 
LOW_RESOLUTION = 0 
IS_DYNAMIC = 1  
DYNAMIC_FAST = 0 
STATIC_FACES = TOP, LEFT, REAR, BOTTOM  
INCLUDE_SKY = 1  
INCLUDE_CARS = 0  
DYNAMIC_LIGHTING = 1   
DEBUG = 0  

[LOCAL_CUBEMAP_...]
MESHES = Cube.060_SUB1
POSITION = -123.13, 1.02, 220.39
OFFSET = 0, 0, 0   
EXCLUDE = 
CLIP_PLANE_NEAR = 2 
HIGH_RESOLUTION = 1 
LOW_RESOLUTION = 0 
IS_DYNAMIC = 1  
DYNAMIC_FAST = 0 
STATIC_FACES = TOP, LEFT, REAR, BOTTOM  
INCLUDE_SKY = 1  
INCLUDE_CARS = 0  
DYNAMIC_LIGHTING = 1   
DEBUG = 0  

[LIGHT_SERIES_...]
CONDITION = NIGHT_SMOOTH
ACTIVE = 1
DESCRIPTION = lightglow
MESHES = Cylinder_004_SUB1
COLOR=1.000000,1.000000,0.500000,10.000000
DIFFUSE_CONCENTRATION=0.880
DIRECTION=0.058684,-0.998274,-0.002925
FADE_AT=500.0
FADE_SMOOTH=200.0
POSITION=-142.147415,10.297599,95.513382
RANGE=15.00
RANGE_GRADIENT_OFFSET=0.100
SHADOWS=1
SHADOWS_BOOST=2.000000
SHADOWS_EXP_FACTOR=10.000000
SHADOWS_EXTRA_BLUR=0
SHADOWS_HALF_RESOLUTION=1
SINGLE_FREQUENCY=0.000
SPECULAR_MULT=1.00
SPOT=150.13
SPOT_SHARPNESS=0.500
VOLUMETRIC_LIGHT=0

[LIGHT_SERIES_0]
CONDITION = SHARP_SUN_B
ACTIVE = 1
DESCRIPTION = lightglow
MESHES = Cube_004_Plate_015_SUB0
DIRECTION = 0,-1,0
SPOT = 140
SPOT_SHARPNESS = 0.5
SHADOWS=1
SHADOWS_BOOST=5.000000
SHADOWS_EXP_FACTOR=10.000000
SHADOWS_EXTRA_BLUR=0
SHADOWS_HALF_RESOLUTION=1
SHADOWS_STATIC=1
RANGE = 80
RANGE_GRADIENT_OFFSET = 0.3
FADE_AT = 300
FADE_SMOOTH = 400
CLUSTER_THRESHOLD = 1
COLOR = 155,83,76,0.015
SINGLE_FREQUENCY = 0.5
 
[LIGHT_SERIES_...]
CONDITION = NIGHT_SMOOTH
ACTIVE = 1
DESCRIPTION = windows
MESHES = Decap.026_SUB1
COLOR=0.806499,0.894690,0.672744,17.110001
DIFFUSE_CONCENTRATION=0.880
DIRECTION_0=-0.458469,-0.281264,0.843028
DIRECTION_1=0.850902,-0.281264,0.443686
DIRECTION_2=0.487611,-0.281264,-0.826516
DIRECTION_3=-0.771019,-0.281264,-0.571335
FADE_AT=500.0
FADE_SMOOTH=200.0
POSITION_0=-19.098640,17.007557,1.154553
POSITION_1=-13.218626,17.007557,-0.266405
POSITION_2=-15.370382,16.899158,-6.106783
POSITION_3=-20.801350,16.899158,-4.611029
RANGE=12.93
RANGE_GRADIENT_OFFSET=0.100
SHADOWS=1
SHADOWS_BOOST=0.000000
SHADOWS_EXP_FACTOR=5.290000
SHADOWS_EXTRA_BLUR=0
SHADOWS_HALF_RESOLUTION=0
SINGLE_FREQUENCY=0.000
SPECULAR_MULT=1.00
SPOT_0=149.34
SPOT_1=175.19
SPOT_2=149.34
SPOT_3=149.34
SPOT_SHARPNESS=0.500
VOLUMETRIC_LIGHT=0
CONDITION = NIGHT_SMOOTH

[LIGHT_...]
ACTIVE=1
COLOR=0.806499,0.894690,0.672744,2.790000
DIFFUSE_CONCENTRATION=0.880
DIRECTION=0.513189,-0.047945,-0.856935
FADE_AT=500.0
FADE_SMOOTH=200.0
POSITION=-16.630032,9.733156,-16.266607
RANGE=23.75
RANGE_GRADIENT_OFFSET=0.100
SHADOWS=1
SHADOWS_BOOST=0.000000
SHADOWS_EXP_FACTOR=0.500000
SHADOWS_EXTRA_BLUR=0
SHADOWS_HALF_RESOLUTION=1
SINGLE_FREQUENCY=0.000
SPECULAR_MULT=1.00
SPOT=143.60
SPOT_SHARPNESS=0.500
VOLUMETRIC_LIGHT=0
CONDITION = NIGHT_SMOOTH

[LIGHT_...]
ACTIVE=1
COLOR=0.806499,0.894690,0.672744,2.790000
DIFFUSE_CONCENTRATION=0.880
DIRECTION=-0.469501,0.008970,0.882886
FADE_AT=500.0
FADE_SMOOTH=200.0
POSITION=-28.311077,9.485846,5.114867
RANGE=23.75
RANGE_GRADIENT_OFFSET=0.100
SHADOWS=1
SHADOWS_BOOST=0.000000
SHADOWS_EXP_FACTOR=2.170000
SHADOWS_EXTRA_BLUR=0
SHADOWS_HALF_RESOLUTION=1
SINGLE_FREQUENCY=0.000
SPECULAR_MULT=1.00
SPOT=143.60
SPOT_SHARPNESS=0.500
VOLUMETRIC_LIGHT=0
CONDITION = NIGHT_SMOOTH

[LIGHT_SERIES_...]
CONDITION = NIGHT_SMOOTH
ACTIVE = 1
DESCRIPTION = spotlights
MESHES = Decap_054
COLOR=0.906165,0.965159,0.967256,2.310000
DIFFUSE_CONCENTRATION=0.880
DIRECTION=0.111703,-0.991869,0.060985
FADE_AT=500.0
FADE_SMOOTH=200.0
POSITION=-14.945222,4.890131,1.727791
RANGE=10.73
RANGE_GRADIENT_OFFSET=0.100
SHADOWS=1
SHADOWS_BOOST=3.140000
SHADOWS_EXP_FACTOR=5.790000
SHADOWS_EXTRA_BLUR=0
SHADOWS_HALF_RESOLUTION=1
SINGLE_FREQUENCY=0.000
SPECULAR_MULT=1.00
SPOT=142.96
SPOT_SHARPNESS=0.500
VOLUMETRIC_LIGHT=0
CLUSTER_THRESHOLD = 1

[LIGHT_...]
ACTIVE = 1
COLOR=1.000000,1.000000,0.500000,2.730000
DIFFUSE_CONCENTRATION=0.880
DIRECTION=0.912363,-0.301601,0.276825
FADE_AT=500.0
FADE_SMOOTH=200.0
POSITION=-441.189392,17.869781,237.238007
RANGE=58.57
RANGE_GRADIENT_OFFSET=0.100
SHADOWS=1
SHADOWS_BOOST=2.000000
SHADOWS_EXP_FACTOR=10.000000
SHADOWS_EXTRA_BLUR=0
SHADOWS_HALF_RESOLUTION=1
SINGLE_FREQUENCY=0.000
SPECULAR_MULT=1.00
SPOT=205.61
SPOT_SHARPNESS=0.500
VOLUMETRIC_LIGHT=0
CONDITION = NIGHT_SMOOTH

[LIGHT_...]
ACTIVE = 1
COLOR=1.000000,1.000000,0.500000,2.730000
DIFFUSE_CONCENTRATION=0.880
DIRECTION=-0.917056,-0.301601,-0.260859
FADE_AT=500.0
FADE_SMOOTH=200.0
POSITION=-452.322998,17.869781,236.581635
RANGE=58.57
RANGE_GRADIENT_OFFSET=0.100
SHADOWS=1
SHADOWS_BOOST=2.000000
SHADOWS_EXP_FACTOR=10.000000
SHADOWS_EXTRA_BLUR=0
SHADOWS_HALF_RESOLUTION=1
SINGLE_FREQUENCY=0.000
SPECULAR_MULT=1.00
SPOT=205.61
SPOT_SHARPNESS=0.500
VOLUMETRIC_LIGHT=0
CONDITION = NIGHT_SMOOTH

[LIGHT_...]
ACTIVE = 1
COLOR=1.000000,1.000000,0.500000,2.730000
DIFFUSE_CONCENTRATION=0.880
FADE_AT=500.0
FADE_SMOOTH=200.0
POSITION=178.249649,20.110317,-518.965698
RANGE=20.61
RANGE_GRADIENT_OFFSET=0.100
SHADOWS=1
SHADOWS_BOOST=1.000000
SHADOWS_EXP_FACTOR=10.000000
SHADOWS_EXTRA_BLUR=0
SHADOWS_HALF_RESOLUTION=1
SINGLE_FREQUENCY=0.000
SPECULAR_MULT=1.00
SPOT=0.00
VOLUMETRIC_LIGHT=0
CONDITION = NIGHT_SMOOTH

[LIGHT_...]
ACTIVE = 1
COLOR=1.000000,1.000000,0.500000,7.760000
DIFFUSE_CONCENTRATION=0.880
FADE_AT=500.0
FADE_SMOOTH=200.0
POSITION=0.120819,1.485497,-50.330585
RANGE=21.41
RANGE_GRADIENT_OFFSET=0.100
SHADOWS=1
SHADOWS_BOOST=0.000000
SHADOWS_EXP_FACTOR=10.000000
SHADOWS_EXTRA_BLUR=0
SHADOWS_HALF_RESOLUTION=0
SINGLE_FREQUENCY=0.000
SPECULAR_MULT=1.00
SPOT=0.00
VOLUMETRIC_LIGHT=0
CONDITION = NIGHT_SMOOTH

[LIGHT_SERIES_2]
CONDITION = NIGHT_SMOOTH
CLUSTER_THRESHOLD = 1
DESCRIPTION = led_light
ACTIVE = 1
MESHES = Cube.004_Plate.015_SUB0
OFFSET = NORMAL
COLOR = 255, 250, 250, 0.01
SPOT = 100
SPOT_SHARPNESS = 0.4
SHADOWS=1
SHADOWS_BOOST=5.000000
SHADOWS_EXP_FACTOR=10.000000
SHADOWS_EXTRA_BLUR=0
SHADOWS_HALF_RESOLUTION=1
SHADOWS_STATIC=1
RANGE = 8
FADE_AT = 100

[LIGHT_SERIES_...]
CONDITION = NIGHT_SMOOTH
ACTIVE = 1
DESCRIPTION = lightglow
MESHES = Decap.052_SUB2
COLOR=1.000000,1.000000,0.500000,10.000000
DIFFUSE_CONCENTRATION=0.880
FADE_AT=500.0
FADE_SMOOTH=200.0
POSITION=-110.427277,2.978570,39.402756
RANGE=15.00
RANGE_GRADIENT_OFFSET=0.100
SHADOWS=1
SHADOWS_BOOST=2.000000
SHADOWS_EXP_FACTOR=10.000000
SHADOWS_EXTRA_BLUR=0
SHADOWS_HALF_RESOLUTION=1
SINGLE_FREQUENCY=0.000
SPECULAR_MULT=1.00
SPOT=0.00
VOLUMETRIC_LIGHT=0

[LIGHT_SERIES_...]
CONDITION = NIGHT_SMOOTH
ACTIVE = 1
DESCRIPTION = marshal_spotlights
MESHES = marshall_B?
COLOR=1,1,0.5,13.75
OFFSET=0,1.05,0
DIFFUSE_CONCENTRATION=0.880
DIRECTION=-0.04469086,-0.9989929,0.004068807
FADE_AT=500.0
FADE_SMOOTH=200.0
RANGE=8.86
RANGE_GRADIENT_OFFSET=0.100
SHADOWS=1
SHADOWS_BOOST=0
SHADOWS_EXP_FACTOR=10
SHADOWS_EXTRA_BLUR=0
SHADOWS_HALF_RESOLUTION=0
SINGLE_FREQUENCY=0.000
SPECULAR_MULT=1.00
SPOT=124.39
SPOT_SHARPNESS=0.500
VOLUMETRIC_LIGHT=0




[MATERIAL_ADJUSTMENT_0]
ACTIVE = 1
DESCRIPTION = lighs_pits
MESHES = Cube_004_Plate_015_SUB0
KEY_0 = ksEmissive
VALUE_0 = 255, 200, 120, 0.8 
VALUE_0_OFF = 0, 0, 0
CONDITION = SHARP_SUN_B
 
[MATERIAL_ADJUSTMENT_1]
ACTIVE = 1
DESCRIPTION = glass
MATERIALS = box_windows
KEY_0 = ksEmissive
VALUE_0 = 255, 195, 105, 0.02
KEY_1 = ksAlphaRef
VALUE_1 = -193
CONDITION = NIGHT_SMOOTH
 
[MATERIAL_ADJUSTMENT_2]
ACTIVE = 1
DESCRIPTION = led_light
MESHES = Mesh1_001
KEY_0 = ksEmissive
VALUE_0 = 255, 10, 10, 10.4
KEY_1 = ksAlphaRef
VALUE_1 = -193
CONDITION = NIGHT_SMOOTH

[MATERIAL_ADJUSTMENT_3]
ACTIVE = 1
DESCRIPTION = led_light
MESHES = Decap_011
KEY_0 = ksEmissive
VALUE_0 = 2.5, 1, 1, 1.4
KEY_1 = ksAlphaRef
VALUE_1 = -193
CONDITION = NIGHT_SMOOTH

[MATERIAL_ADJUSTMENT_4]
ACTIVE = 1
DESCRIPTION = lighs_pits
MESHES =  Decap_054
KEY_0 = ksEmissive
VALUE_0 = 250, 250, 255, 0.8 
VALUE_0_OFF = 0, 0, 0
CONDITION = NIGHT_SMOOTH

[MATERIAL_ADJUSTMENT_5]
ACTIVE = 1
DESCRIPTION = lighs_pits
MESHES = Cylinder_004_SUB1
KEY_0 = ksEmissive
VALUE_0 = 255, 200, 150, 0.8 
VALUE_0_OFF = 0, 0, 0
CONDITION = NIGHT_SMOOTH
 
[GRASS_FX]
GRASS_MATERIALS = grass, blend_grass, Background
OCCLUDING_MATERIALS_ALPHA = 
OCCLUDING_MATERIALS = kerb, ast, Plane.001, post
OCCLUDING_MESHES_ALPHA = 
OCCLUDING_MESHES = 


MASK_BLUR = 1 ; from 0 to 3, 0 to disable blur

SHAPE_SIZE = 1, 2
SHAPE_TIDY = 0
SHAPE_CUT = 0
TRIM_PERIOD = 365

; special texture
TEXTURE = grass_fx/highlands.dds
TEXTURE_GRID = 8, 3 

[GRASS_FX_TEXTURE_GROUP_0]
PIECE_0 = 1, 1
PIECE_0_CHANCE = 0.25
PIECE_1 = 1, 2, 2, 1
PIECE_1_CHANCE = 0.05
PIECE_2 = 4, 1, 2, 2
PIECE_2_CHANCE = 0.5
PIECE_3 = 6, 1
PIECE_4 = 7, 1
PIECE_5 = 8, 1


[GRASS_FX_CONFIGURATION_A]
SHAPE_SIZE = 4.0, 3.5
SHAPE_CUT = 1, 0
SHAPE_TIDY = 1, 0.5
TRIM_PERIOD = 30
MASK_MAIN_THRESHOLD = 0.6
MASK_MAX_LUMINANCE = 0.1
TEXTURE_BASE_CHANCE = 1
TEXTURE_GROUP_0_CHANCE = 0.2

[GRASS_FX_CONFIGURATION_B]
SHAPE_SIZE = 3.5, 6.0
SHAPE_CUT = 0
SHAPE_TIDY = 0
TRIM_PERIOD = 365
MASK_MAIN_THRESHOLD = 0.4
MASK_MAX_LUMINANCE = 0.105
TEXTURE_BASE_CHANCE = 1
TEXTURE_GROUP_0_CHANCE = 0.5

[GRASS_FX_ADJUSTMENT_...]
MATERIALS = grass, blend_grass
MAP = A

[GRASS_FX_ADJUSTMENT_...]
MATERIALS = Background
MAP = B

 

[RAIN_FX]
PUDDLES_MATERIALS = road_main, ast, txt, DN
SOAKING_MATERIALS = grass, sand, Background
SMOOTH_MATERIALS = armco, armco_c, banner2, wall_shini,box_red
ROUGH_MATERIALS = tree1

[MATERIAL_ADJUSTMENT_...]
MATERIALS=grass, sand
KEY_0=ksAlphaRef
VALUE_0=-193
VALUE_0_OFF=-193

[SHADER_REPLACEMENT_...]
ACTIVE = 1
MESHES = Cube.060_SUB1,Cube.055_SUB1
SHADER = ksPerPixelReflection
PROP_... = fresnelC,0.84
PROP_... = fresnelEXP, 10
PROP_... = fresnelMaxLevel, 0.4
PROP_... = ksSpecularEXP, 1000
PROP_... = ksSpecular, 9 

[SHADER_REPLACEMENT_...]
ACTIVE = 1
MESHES = Decap.026_SUB1,Decap.025_SUB2
PROP_... = fresnelC,0.84
PROP_... = kresnelEXP, 10
PROP_... = fresnelMaxLevel, 0.4
PROP_... = ksSpecularEXP, 1000
PROP_... = ksSpecular, 9 

[SHADER_REPLACEMENT_...] 
SHADER = ksPerPixelMultiMap_NMDetail ; ksPerPixelNormalMap_UVMult 
MATERIALS = sand
RESOURCE_1 = txNormal
RESOURCE_FILE_1 = 2sand_normal.dds
PROP_... = NormalMult, 2
FILL_MISSING_TEXTURES = 1

[CONDITION_...]
NAME=MYRACING_FLAG
INPUT=FLAG_TYPE
LUT=(|1=0,1,0|2=1,1,0|3=1,0.5,0|4=1,0.3,0|5=1,0,0|6=0.7,0.7,0.7|7=1,0.5,0.5|8=0.1,0.1,0.1|9=0,0,0.1|10=0.5,0.5,0.5|11=0.5,0.5,0.5|12=0,0,1.5|13=0,0,0|14=1,1,1|)
FLASHING_FREQUENCY=0.2
FLASHING_SMOOTHNESS=0

[CONDITION_...]
NAME = RACING_FLAG_NO_GREEN
INPUT = FLAG_TYPE
LUT = (|1=0,0,0|2=1,0.75,0|3=1,0.5,0|4=1,0.3,0|5=1,0,0|6=0.7,0.7,0.7|7=1,0.5,0.5|8=0.1,0.1,0.1|9=0,0,0.1|10=0.5,0.5,0.5|11=0.5,0.5,0.5|12=0,0,1|13=0,0,0|14=1,1,1|)
FLASHING_FREQUENCY=8
FLASHING_SMOOTHNESS=0
 
[CONDITION_...]
NAME = RACING_FLAG_NO_BLUE
INPUT = FLAG_TYPE
LUT = (|1=0,1,0|2=1,0.75,0|3=1,0.5,0|4=1,0.3,0|5=1,0,0|6=0.7,0.7,0.7|7=1,0.5,0.5|8=0.1,0.1,0.1|9=0,0,0.1|10=0.5,0.5,0.5|11=0.5,0.5,0.5|12=0,0,1|13=0,0,0|14=1,1,1|)
INPUT_STAY_FOR = .2
INPUT_CHANGE_DELAY = .2
 
[CONDITION_...]
NAME = RACING_FLAG_NO_BLUE_GREEN
INPUT = FLAG_TYPE
LUT = (|1=0,0,0|2=1,0.75,0|3=1,0.5,0|4=1,0.3,0|5=1,0,0|6=0.7,0.7,0.7|7=1,0.5,0.5|8=0.1,0.1,0.1|9=0,0,0.1|10=0.5,0.5,0.5|11=0.5,0.5,0.5|12=0,0,0|13=0,0,0|14=1,1,1|)
FLASHING_FREQUENCY=8
FLASHING_SMOOTHNESS=0

[MATERIAL_ADJUSTMENT_...]
DESCRIPTION = digital flags pit exit
MESHES = Decap.004_SUB2
ACTIVE = 1
KEY_0 = ksEmissive
VALUE_0 = 20,20,20,1
KEY_1 = ksAlphaRef
VALUE_1 = -193
KEY_2 = ksDiffuse
VALUE_2 = 0
KEY_3 = ksSpecular
VALUE_3 = 0
KEY_4 = nmObjectSpace
VALUE_4 = 0
CONDITION = RACING_FLAG_NO_BLUE

[LIGHT_...]
INPUT=LUT
DIFFUSE_CONCENTRATION=0.880
DIRECTION=0.52469796,-0.400634,-0.7511222
FADE_AT=500.0
FADE_SMOOTH=200.0
POSITION=-123.82365,2.5691743,222.5707
RANGE=23.51
RANGE_GRADIENT_OFFSET=0.100
SHADOWS=1
SHADOWS_BOOST=0
SHADOWS_EXP_FACTOR=10
SHADOWS_EXTRA_BLUR=0
SHADOWS_HALF_RESOLUTION=0
SINGLE_FREQUENCY=0.000
SPECULAR_MULT=1.00
SPOT=134.62
SPOT_SHARPNESS=0.500
VOLUMETRIC_LIGHT=0
CONDITION = RACING_FLAG_NO_BLUE

 
[MATERIAL_ADJUSTMENT_...]
DESCRIPTION = digital flags traverse
MESHES =Decap.053
ACTIVE = 1
KEY_0 = ksEmissive
VALUE_0 = 20,20,20,10
KEY_1 = ksAlphaRef
VALUE_1 = -193
KEY_2 = ksDiffuse
VALUE_2 = 0
KEY_3 = ksSpecular
VALUE_3 = 0
KEY_4 = nmObjectSpace
VALUE_4 = 0
CONDITION = MYRACING_FLAG

[LIGHT_...]
INPUT=LUT
DIFFUSE_CONCENTRATION=0.880
DIRECTION=0.45471686,-0.3534198,-0.8175138
FADE_AT=500.0
FADE_SMOOTH=200.0
POSITION=-28.91312,5.4833565,67.99459
RANGE=23.51
RANGE_GRADIENT_OFFSET=0.100
SHADOWS=1
SHADOWS_BOOST=0
SHADOWS_EXP_FACTOR=10
SHADOWS_EXTRA_BLUR=0
SHADOWS_HALF_RESOLUTION=0
SINGLE_FREQUENCY=0.000
SPECULAR_MULT=1.00
SPOT=134.62
SPOT_SHARPNESS=0.500
VOLUMETRIC_LIGHT=0
CONDITION = MYRACING_FLAG

[LIGHT_...]
INPUT=LUT
DIFFUSE_CONCENTRATION=0.880
DIRECTION=-0.4274237,-0.4818422,0.7649427
FADE_AT=500.0
FADE_SMOOTH=200.0
POSITION=-32.289036,5.571592,68.07931
RANGE=23.51
RANGE_GRADIENT_OFFSET=0.100
SHADOWS=1
SHADOWS_BOOST=0
SHADOWS_EXP_FACTOR=10
SHADOWS_EXTRA_BLUR=0
SHADOWS_HALF_RESOLUTION=0
SINGLE_FREQUENCY=0.000
SPECULAR_MULT=1.00
SPOT=134.62
SPOT_SHARPNESS=0.500
VOLUMETRIC_LIGHT=0
CONDITION = MYRACING_FLAG

 
[MATERIAL_ADJUSTMENT_...]
DESCRIPTION = digital flags
MESHES = 
ACTIVE = 1
KEY_0 = ksEmissive
VALUE_0 = 20,20,20,10
KEY_1 = ksAlphaRef
VALUE_1 = -193
KEY_2 = ksDiffuse
VALUE_2 = 0
KEY_3 = ksSpecular
VALUE_3 = 0
KEY_4 = nmObjectSpace
VALUE_4 = 0
CONDITION = RACING_FLAG_NO_GREEN


[LIGHT_...]
ACTIVE = 1 
COLOR=0.284844,0.850132,0.149868,3.000000
DIFFUSE_CONCENTRATION=0.782
DIRECTION=0.390048,-0.160248,-0.906744
FADE_AT=500.0
FADE_SMOOTH=200.0
POSITION=-123.690620,1.903972,222.732605
RANGE=7.09
RANGE_GRADIENT_OFFSET=0.100
SHADOWS=1
SHADOWS_BOOST=2.5
SHADOWS_EXP_FACTOR=10.000000
SHADOWS_EXTRA_BLUR=0
SHADOWS_HALF_RESOLUTION=1
SINGLE_FREQUENCY=0.000
SPECULAR_MULT=1.00
SPOT=130.82
SPOT_SHARPNESS=0.500
VOLUMETRIC_LIGHT=0
CONDITION = RACING_FLAG_NO_BLUE
