
[ABOUT]
AUTHOR = Den_88
VERSION = 1.7
 
[INCLUDE]
INCLUDE =  common/conditions.ini, common/conditions_blm.ini, common/materials_track.ini, common/custom_emissive.ini, common/grass_fx.ini

[LIGHTING]
SPECULAR_MULT=1
LIT_MULT=1 

[BOUNCED_LIGHT]
SUPPORTED = 1
SURFACE_MATERIALS = ?
OCCLUDING_MATERIALS = 
OBJECT_MATERIALS = ?

[SOL]
HORIZON_OFFSET = 0.1
DOME_SIZE = 24000
SUN_DAWN = 1
SUN_DUSK = 1
FOG_LEVEL = 0.90
FOG_BLEND = 1.15
FOG_DISTANCE = 0.9
SMOG_MORNING = 0.5
SMOG_NOON = 0.1
SMOG_EVENING = 0.15
EXPOSURE_FIX = 1

[SOL2]
HUMIDITY_OFFSET = 0.98

[PURE]
FOG_BLEND = 1.15
SMOG_EVENING = 0.15
ACTIVE= 1
SUN_DAWN = 1
SMOG_MORNING = 0.05
FOG_LEVEL = 0.05
SUN_DUSK = 1
SMOG_NOON = 0.1
FOG_DISTANCE = 0.9

[BASIC]
SUPPORTS_WIND = 1

[WIND]
DYNAMIC_FLAGS = AUTO
DYNAMIC_FLAGS_TESSELLATION = 1

[SHADER_REPLACEMENT_...]
ACTIVE = 1
MATERIALS = Material #54,
IS_TRANSPARENT = 1
BLEND_MODE = ALPHA_BLEND
DOUBLE_FACE_SHADOW_BIASED = 1
CULL_MODE = NONE
PROP_... = ksAlphaRef,0.5

[LIGHT_SERIES_...]
CONDITION = NIGHT_SMOOTH
ACTIVE = 1
DESCRIPTION = light
MATERIALS = otragatel
DIRECTION = 0,-1,0
SPOT = 200
SPOT_SHARPNESS = 0.5
RANGE = 80
RANGE_GRADIENT_OFFSET = 0.3
FADE_AT = 300
FADE_SMOOTH = 400
CLUSTER_THRESHOLD = 15
COLOR = 255,183,76,0.055
SINGLE_FREQUENCY = 0.5
 
[LIGHT_SERIES_...]
CONDITION = NIGHT_SMOOTH
ACTIVE = 1
DESCRIPTION = windows
MATERIALS = window1_MH, Material #45.001, mh_window1, mh_window5
DIRECTION = 0,-1,0
SPOT = 200
SPOT_SHARPNESS = 0.5
RANGE = 60
RANGE_GRADIENT_OFFSET = 0.3
FADE_AT = 400
FADE_SMOOTH = 10
CLUSTER_THRESHOLD = 15
COLOR = 255,183,76,0.025
SINGLE_FREQUENCY = 0.5

[LIGHT_SERIES_...]
CONDITION = NIGHT_SMOOTH
ACTIVE = 1
DESCRIPTION = windows
MATERIALS = led_logo
DIRECTION = 0,-1,0
SPOT = 300
SPOT_SHARPNESS = 0.5
RANGE = 30
RANGE_GRADIENT_OFFSET = 0.3
FADE_AT = 400
FADE_SMOOTH = 10
CLUSTER_THRESHOLD = 15
COLOR = 200,200,200,0.025
SINGLE_FREQUENCY = 0.5


[MATERIAL_ADJUSTMENT_...]
ACTIVE = 1
DESCRIPTION = glass
MATERIALS = window1_MH, mh_window1, mh_window4, Material #47.001, Material #46.001, Material #45.001, Material #58, Material #57,  Material #56, mc_okna1, mc_okna2, mh_window, mh_window6, mh_window5, mh_window2,
KEY_0 = ksEmissive
VALUE_0 = 255,183,76,0.01
VALUE_0_OFF = 0, 0, 0
CONDITION = NIGHT_SMOOTH

[MATERIAL_ADJUSTMENT_...]
ACTIVE = 1
DESCRIPTION = glass
MATERIALS =  otragatel
KEY_0 = ksEmissive
VALUE_0 = 255,183,76,0.51
VALUE_0_OFF = 0, 0, 0
CONDITION = NIGHT_SMOOTH
 
 
[MATERIAL_ADJUSTMENT_...]
ACTIVE = 1
DESCRIPTION = glass
MATERIALS = glow
KEY_0 = ksEmissive
VALUE_0 = 255,195,105,0.02
KEY_1 = ksAlphaRef
VALUE_1 = -193
CONDITION = NIGHT_SMOOTH
 
[MATERIAL_ADJUSTMENT_...]
ACTIVE = 1
DESCRIPTION = red_light
MESHES = MH.005_SUB20
KEY_0 = ksEmissive
VALUE_0 = 255, 0, 0, 0.25
KEY_1 = ksAlphaRef
VALUE_1 = -193
CONDITION = NIGHT_SMOOTH

[MATERIAL_ADJUSTMENT_...]
ACTIVE = 1
;VISIBILITY_LEVEL = 0
DESCRIPTION = marshal flag
MESHES = Decap.027_SUB1,Cube.033_SUB1,
KEY_0 = ksEmissive
VALUE_0 = 25, 25, 25, 1
KEY_1 = ksAlphaRef
VALUE_1 = -193
CONDITION = RACING_FLAG_NO_BLUE_GREEN

[MATERIAL_ADJUSTMENT_...]
ACTIVE = 1
;VISIBILITY_LEVEL = 0
DESCRIPTION = marshal flag
MESHES = Decap.015,Decap.017,
KEY_0 = ksEmissive
VALUE_0 = 25, 25, 25, 4
KEY_1 = ksAlphaRef
VALUE_1 = -193
; KEY_2 = ksDiffuse
; VALUE_2 = 0
VALUE_2_OFF = ORIGINAL
CONDITION = MYRACING_FLAG

[MATERIAL_ADJUSTMENT_...]
DESCRIPTION = digital flags pit exit
MESHES = Decap_SUB2
ACTIVE = 1
KEY_0 = ksEmissive
VALUE_0 = 20,20,20,1
KEY_1 = ksAlphaRef
VALUE_1 = -193
CONDITION = RACING_FLAG_NO_BLUE

[CONDITION_...]
NAME = MYRACING_FLAG
INPUT = FLAG_TYPE
LUT = (|1=0,1,0|2=1,1,0|3=1,0.5,0|4=1,0.3,0|5=1,0,0|6=0.7,0.7,0.7|7=1,0.5,0.5|8=0.1,0.1,0.1|9=0,0,0.1|10=0.5,0.5,0.5|11=0.5,0.5,0.5|12=0,0,1.5|13=0,0,0|14=1,1,1|)
FLASHING_FREQUENCY = 0.2
FLASHING_SMOOTHNESS = 0

[CONDITION_...]
NAME = RACING_FLAG_NO_GREEN
INPUT = FLAG_TYPE
LUT = (|1=0,0,0|2=1,0.75,0|3=1,0.5,0|4=1,0.3,0|5=1,0,0|6=0.7,0.7,0.7|7=1,0.5,0.5|8=0.1,0.1,0.1|9=0,0,0.1|10=0.5,0.5,0.5|11=0.5,0.5,0.5|12=0,0,1|13=0,0,0|14=1,1,1|)
FLASHING_FREQUENCY=8
FLASHING_SMOOTHNESS=0
 
[CONDITION_...]
NAME = RACING_FLAG_NO_BLUE
INPUT = FLAG_TYPE
LUT = (|1=0,1,0|2=1,0.75,0|3=1,0.5,0|4=1,0.3,0|5=1,0,0|6=0.7,0.7,0.7|7=1,0.5,0.5|8=0.1,0.1,0.1|9=0,0,0.1|10=0.5,0.5,0.5|11=0.5,0.5,0.5|12=0,0,1|13=0,0,0|14=1,1,1|)
INPUT_STAY_FOR = .2
INPUT_CHANGE_DELAY = .2

[CONDITION_...]
NAME = RACING_FLAG_NO_BLUE_GREEN
INPUT = FLAG_TYPE
LUT = (|1=0,0,0|2=1,0.75,0|3=1,0.5,0|4=1,0.3,0|5=1,0,0|6=0.7,0.7,0.7|7=1,0.5,0.5|8=0.1,0.1,0.1|9=0,0,0.1|10=0.5,0.5,0.5|11=0.5,0.5,0.5|12=0,0,0|13=0,0,0|14=1,1,1|)
FLASHING_FREQUENCY=8
FLASHING_SMOOTHNESS=0
 
[LIGHT_...]
DESCRIPTION=digital flags pit exit
INPUT=LUT
DIFFUSE_CONCENTRATION=0.880
DIRECTION=0.03336045,-0.39263588,0.91908884
FADE_AT=500.0
FADE_SMOOTH=200.0
POSITION=481.26285,1.5362782,-7.4955044
RANGE=4.00
RANGE_GRADIENT_OFFSET=0.100
SHADOWS=1
SHADOWS_BOOST=0
SHADOWS_EXP_FACTOR=10
SHADOWS_EXTRA_BLUR=0
SHADOWS_HALF_RESOLUTION=0
SINGLE_FREQUENCY=0.000
SPECULAR_MULT=1.00
SPOT=130.55
SPOT_SHARPNESS=0.500
VOLUMETRIC_LIGHT=0
CLUSTER_THRESHOLD=1
CONDITION=RACING_FLAG_NO_BLUE

[LIGHT_SERIES_...]
DESCRIPTION=digital flags start traverse
INPUT=LUT
DIFFUSE_CONCENTRATION=0.880
DIRECTION=0,-1,0
FADE_AT=500.0
FADE_SMOOTH=200.0
MESHES=Cube.033_SUB1
RANGE=7.00
RANGE_GRADIENT_OFFSET=0.100
SHADOWS=1
SHADOWS_BOOST=0
SHADOWS_EXP_FACTOR=10
SHADOWS_EXTRA_BLUR=0
SHADOWS_HALF_RESOLUTION=0
SINGLE_FREQUENCY=0.000
SPECULAR_MULT=1.00
SPOT=130.55
SPOT_SHARPNESS=0.500
VOLUMETRIC_LIGHT=0
CLUSTER_THRESHOLD=1
CONDITION=RACING_FLAG_NO_BLUE_GREEN

[LIGHT_SERIES_...]
DESCRIPTION=digital flags 
INPUT=LUT
DIFFUSE_CONCENTRATION=0.880
DIRECTION=0,-1,0
FADE_AT=500.0
FADE_SMOOTH=200.0
MESHES=Decap.015,Decap.017
RANGE=2.5
RANGE_GRADIENT_OFFSET=0.100
SHADOWS=1
SHADOWS_BOOST=0
SHADOWS_EXP_FACTOR=10
SHADOWS_EXTRA_BLUR=0
SHADOWS_HALF_RESOLUTION=0
SINGLE_FREQUENCY=0.000
SPECULAR_MULT=1.00
SPOT=130.55
SPOT_SHARPNESS=0.500
VOLUMETRIC_LIGHT=0
CLUSTER_THRESHOLD=1
CONDITION=MYRACING_FLAG

[LIGHT_...]
DESCRIPTION=digital flags start traverse
INPUT=LUT
DIFFUSE_CONCENTRATION=0.880
DIRECTION=0.02459061,-0.22320439,0.9744615
FADE_AT=500.0
FADE_SMOOTH=200.0
POSITION=479.92355,5.0231214,144.1038
RANGE=6.00
RANGE_GRADIENT_OFFSET=0.100
SHADOWS=1
SHADOWS_BOOST=0
SHADOWS_EXP_FACTOR=10
SHADOWS_EXTRA_BLUR=0
SHADOWS_HALF_RESOLUTION=0
SINGLE_FREQUENCY=0.000
SPECULAR_MULT=1.00
SPOT=172.78
SPOT_SHARPNESS=0.500
VOLUMETRIC_LIGHT=0
CLUSTER_THRESHOLD=1
CONDITION=RACING_FLAG_NO_BLUE_GREEN


[CustomEmissive]
ACTIVE = 1
DESCRIPTION = marshalllight
MESHES = Decap.015,Decap.017
Resolution = 32, 32
@ = CustomEmissive_Rect, Channel = 0,Start = "15.570, 23.011", Size = "7.742, 8.258",CornerRadius = 1,1,Intensity = 3

[MATERIAL_ADJUSTMENT_...]
MATERIALS=line,misc4,tr_white
KEY_0=extBounceBack
VALUE_0=0.4
VALUE_0_OFF=-193

 
[GRASS_FX]
GRASS_MATERIALS = gras1, grass2, Material_SputnikMap
OCCLUDING_MATERIALS_ALPHA = 
OCCLUDING_MATERIALS = carpet1, cerb_new, misc4
OCCLUDING_MESHES_ALPHA = 
OCCLUDING_MESHES = KERB


MASK_BLUR = 1 ; from 0 to 3, 0 to disable blur

SHAPE_SIZE = 1, 2
SHAPE_TIDY = 0
SHAPE_CUT = 0
TRIM_PERIOD = 365

; special texture
TEXTURE = grass_fx/highlands.dds ; should look like that: https://i.imgur.com/FEEpsCh.png
TEXTURE_GRID = 8, 3 ; horizontal and vertical slots; first row of slots is used by default

[GRASS_FX_TEXTURE_GROUP_0]
PIECE_0 = 1, 1
PIECE_0_CHANCE = 0.25
PIECE_1 = 1, 2, 2, 1
PIECE_1_CHANCE = 0.05
PIECE_2 = 4, 1, 2, 2
PIECE_2_CHANCE = 0.5
PIECE_3 = 6, 1
PIECE_4 = 7, 1
PIECE_5 = 8, 1


[GRASS_FX_CONFIGURATION_A]
SHAPE_SIZE = 1.3, 2.0
SHAPE_CUT = 1, 0
SHAPE_TIDY = 1, 0.5
TRIM_PERIOD = 30
MASK_MAIN_THRESHOLD = 0.6
MASK_MAX_LUMINANCE = 0.2
TEXTURE_BASE_CHANCE = 1
TEXTURE_GROUP_0_CHANCE = 0.2

[GRASS_FX_CONFIGURATION_B]
SHAPE_SIZE = 3.5, 6.0
SHAPE_CUT = 0
SHAPE_TIDY = 0
TRIM_PERIOD = 365
MASK_MAIN_THRESHOLD = 0.4
MASK_MAX_LUMINANCE = 0.105
TEXTURE_BASE_CHANCE = 1
TEXTURE_GROUP_0_CHANCE = 0.5

[GRASS_FX_CONFIGURATION_C]
SHAPE_SIZE = 2.5, 3.0
SHAPE_CUT = 0
SHAPE_TIDY = 0
TRIM_PERIOD = 365
MASK_MAIN_THRESHOLD = 0.4
MASK_MAX_LUMINANCE = 0.2
TEXTURE_BASE_CHANCE = 1
TEXTURE_GROUP_0_CHANCE = 0.5

[GRASS_FX_ADJUSTMENT_...]
MATERIALS = gras1
MAP = A

[GRASS_FX_ADJUSTMENT_...]
MATERIALS = Material_SputnikMap
MAP = B

[GRASS_FX_ADJUSTMENT_...]
MATERIALS = grass2
MAP = C


 

[RAIN_FX]
PUDDLES_MATERIALS = roads, carpet1, cerb_new, cerb_paint, asphalt_red, Griles, dn, line, pit_beton, MH_roof1, asphalt2
SOAKING_MATERIALS = gras1, grass2, sand1, blend_mask, blend_mask2, blend_mask3, Material_SputnikMap
SMOOTH_MATERIALS = armco, armco_c, banner2, wall_shini, wall_n, sa_metals, misc4, black, tent, logo2, Material #91
ROUGH_MATERIALS = tree1

[MATERIAL_ADJUSTMENT_...]
MATERIALS= gras1, grass2, sand1
KEY_0=ksAlphaRef
VALUE_0=-193
VALUE_0_OFF=-193


[WRAP_MESHES_...]
NAME = blades_1
MESHES = Helicopter_screw_b001
PIVOT_POS = 275.91, 0.863, 283.63               

[ANIMATED_...]
NODE = blades_1
WINDMILL_DIR = 1, 1, 1
WINDMILL_DIR_EXP = 0.5
WINDMILL_DIR_BOTH_SIDES = 1
SPIN_AXIS = 0, 1, 0
SPEED_MULT = 0.3
WIND_SPEED_KMH_MIN = 1
WIND_SPEED_KMH_MAX = 20
WIND_SPEED_KMH_STOP = 40
LAG_UP = 0.998
LAG_DOWN = 0.998
LAG_BRAKING = 0.98

[WRAP_MESHES_...]
NAME = blades_2
MESHES = Helicopter_screw_s001
PIVOT_POS = 281.61, -0.425, 283.82               

[ANIMATED_...]
NODE = blades_2
WINDMILL_DIR = 1, 1, 1
WINDMILL_DIR_EXP = 0.5
WINDMILL_DIR_BOTH_SIDES = 1
SPIN_AXIS = 0, 0, 1
SPEED_MULT = 0.9
WIND_SPEED_KMH_MIN = 1
WIND_SPEED_KMH_MAX = 20
WIND_SPEED_KMH_STOP = 40
LAG_UP = 0.998
LAG_DOWN = 0.998
LAG_BRAKING = 0.98

[MATERIAL_ADJUSTMENT_...]
DESCRIPTION=led walls lcd screens
MATERIALS = mh_display
KEY_0=ksEmissive
VALUE_0=255,255,255,0.1
VALUE_0_OFF=ORIGINAL
CONDITION=ALWAYS_ON

[DISPLAY_...] ;  0
MESHES = MH.005_SUB11,
REGION_START = 0, 0   ; display position on texture, in pixels
REGION_SIZE = 900, 600   ; display size on texture, in pixels

HIGH_REFRESH_RATE = 1    ; high refresh rate (enabled by default; 30 FPS with this option on, 15 FPS without)
FLIP_X = 1               ; change to 1 to flip output on X axis (mainly for strange UV mapping)
FLIP_Y = 1               ; change to 1 to flip output on Y axis (mainly for strange UV mapping)

OUTPUT_ALPHA = 1         ; alpha channel value for display area
OUTPUT_GAMMA = 0.55      ; gamma correction, reduce to make darker areas even darker
OUTPUT_SATURATION = 1.0  ; saturation correction
OUTPUT_BRIGHTNESS = 1.0  ; brightness correction
OUTPUT_FISH_EYE = 0.0    ; increase to add lens distortion effect
OUTPUT_VIGNETTE = 0.0    ; increase to darken corners
OUTPUT_CHROMATIC_ABERRATION = 0.0 ; increase to add that nasty chromatic aberration
MODE = CAMERA

CAMERA_0 = 505.405 ,6.90695 ,-117.545
CAMERA_0_TARGET = FOCUSED_CAR ; instead of fixed point, uses closes car
CAMERA_0_TARGET_INERTIA = 0.1  ; camera inertia for smoother movement
CAMERA_0_FOV = 25

CAMERA_1 = 287.279 ,6.9504 ,-161.058
CAMERA_1_TARGET = 288, 3, 160  ; instead of fixed point, uses closes car
CAMERA_1_TARGET_INERTIA = 0.1  ; camera inertia for smoother movement
CAMERA_1_FOV = 15

CAMERA_2 = 200.027 ,8.25161 ,248.158
CAMERA_2_TARGET = -170, 8, -60  ; instead of fixed point, uses closes car
CAMERA_2_TARGET_INERTIA = 0.1  ; camera inertia for smoother movement
CAMERA_2_FOV = 25

CAMERA_3 = 226.797 ,5.09162 ,-11.3382
CAMERA_3_TARGET = FOCUSED_CAR  ; instead of fixed point, uses closes car
CAMERA_3_TARGET_INERTIA = 0.1  ; camera inertia for smoother movement
CAMERA_3_FOV = 25

CAMERA_4 = -125.865 ,-6.48886 ,40.1429
CAMERA_4_TARGET = FOCUSED_CAR  ; instead of fixed point, uses closes car
CAMERA_4_TARGET_INERTIA = 0.1  ; camera inertia for smoother movement
CAMERA_4_FOV = 25
